# Generated by Django 4.0.5 on 2022-07-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
