# Generated by Django 4.0.5 on 2022-07-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_todoentry_delete_todonote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
        migrations.DeleteModel(
            name='ToDoEntry',
        ),
    ]
